# K1 model

In [27]:
import csv
import pickle
import numpy as np
import pandas as pd
import matplotlib as plt
from numpy import array
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score
from sklearn.model_selection import KFold
from sklearn.cross_validation import cross_val_score 
from sklearn.metrics import accuracy_score,precision_score, recall_score, confusion_matrix, precision_recall_curve
from sklearn.feature_selection import SelectKBest, mutual_info_classif, chi2
from sklearn.metrics import classification_report,confusion_matrix

#load the pickle file
dataK1 = pickle.load(open("data/feature_selection/feature_k=1.pkl",'rb'))

print(dataK1['categorical'].shape)
print(dataK1['numerical'].shape)

#X = np.concatenate((dataK1['categorical'],dataK1['numerical']),axis=1)
X = np.array(dataK1['numerical'])
y = []
for i in range(41188):
    y.append(dataK1['categorical'][i][2])

#Convert list to np array
y = np.asarray(y)

#Initialize K-fold
kf = KFold(n_splits = 5, random_state= 5)

#K1 model 
for train_indices, test_indices in kf.split(X):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state = 0)
    lg = LogisticRegression()
    lg = lg.fit(X[train_indices], y[train_indices])
    y_pred_test = lg.predict(X_test)

    CM = confusion_matrix(y_pred=y_pred_test, y_true=y_test)
    acs = accuracy_score(y_true=y_test, y_pred=y_pred_test, normalize=True, sample_weight=None)
    f1score = f1_score(y_test, y_pred_test, average='macro') 
    recall = recall_score(y_test, y_pred_test, average='macro')  
    precision = precision_score(y_test, y_pred_test, average='macro')  
    kfold = cross_val_score(estimator = lg, X = X[train_indices], y = y[train_indices], cv = 5)

    print('Confusion Matrix: \n',CM)
    print('Accuracy Score: ',acs)
    print('Recall:', recall)
    print('F1-Score:', f1score)
    print('Precision:', precision)
    print("5-Fold Cross Vaildation:", kfold.mean())
    print('\n')
    print(confusion_matrix(y_test,y_pred_test))
    print(classification_report(y_test,y_pred_test))



(41188, 3)
(41188, 1)
Confusion Matrix: 
 [[9745    0]
 [2612    0]]
Accuracy Score:  0.7886218337784252
Recall: 0.5
F1-Score: 0.44091032485747894
Precision: 0.3943109168892126
5-Fold Cross Vaildation: 0.8183308071804689


[[9745    0]
 [2612    0]]


/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/anaconda3/lib/python3.6/site-packages/sklearn/metrics/clas

             precision    recall  f1-score   support

        0.0       0.79      1.00      0.88      9745
        1.0       0.00      0.00      0.00      2612

avg / total       0.62      0.79      0.70     12357

Confusion Matrix: 
 [[9745    0]
 [2612    0]]
Accuracy Score:  0.7886218337784252
Recall: 0.5
F1-Score: 0.44091032485747894
Precision: 0.3943109168892126
5-Fold Cross Vaildation: 0.8094688979620859


[[9745    0]
 [2612    0]]


/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


             precision    recall  f1-score   support

        0.0       0.79      1.00      0.88      9745
        1.0       0.00      0.00      0.00      2612

avg / total       0.62      0.79      0.70     12357

Confusion Matrix: 
 [[9745    0]
 [2612    0]]
Accuracy Score:  0.7886218337784252
Recall: 0.5
F1-Score: 0.44091032485747894
Precision: 0.3943109168892126
5-Fold Cross Vaildation: 0.797238242494539


[[9745    0]
 [2612    0]]
             precision    recall  f1-score   support

        0.0       0.79      1.00      0.88      9745
        1.0       0.00      0.00      0.00      2612

avg / total       0.62      0.79      0.70     12357



/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/anaconda3/lib/python3.6/site-packages/sklearn/metrics/clas

Confusion Matrix: 
 [[9745    0]
 [2612    0]]
Accuracy Score:  0.7886218337784252
Recall: 0.5
F1-Score: 0.44091032485747894
Precision: 0.3943109168892126
5-Fold Cross Vaildation: 0.7746654114487751


[[9745    0]
 [2612    0]]
             precision    recall  f1-score   support

        0.0       0.79      1.00      0.88      9745
        1.0       0.00      0.00      0.00      2612

avg / total       0.62      0.79      0.70     12357

Confusion Matrix: 
 [[9745    0]
 [2612    0]]
Accuracy Score:  0.7886218337784252
Recall: 0.5
F1-Score: 0.44091032485747894
Precision: 0.3943109168892126
5-Fold Cross Vaildation: 0.7566689990275652


[[9745    0]
 [2612    0]]
             precision    recall  f1-score   support

        0.0       0.79      1.00      0.88      9745
        1.0       0.00      0.00      0.00      2612

avg / total       0.62      0.79      0.70     12357



/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


# K3 Model 

In [17]:
dataK3 = pickle.load(open("data/feature_selection/feature_k=3.pkl",'rb'))

Xc = dataK3['categorical'][:,:11]
Xn = dataK3['numerical'][:,:5]
X = np.concatenate((Xc,Xn),axis=1)

y = []
for i in range(41188):
    y.append(dataK3['categorical'][i][12])

#Convert list to np array
y = np.asarray(y)

#Initialize K-fold
kf = KFold(n_splits = 5, random_state= 20)

#K1 model 
for train_indices, test_indices in kf.split(X):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)
    lg = LogisticRegression()
    lg = lg.fit(X[train_indices], y[train_indices])
    y_pred_test = lg.predict(X_test)

    CM = confusion_matrix(y_pred=y_pred_test, y_true=y_test)
    acs = accuracy_score(y_true=y_test, y_pred=y_pred_test, normalize=True, sample_weight=None)
    f1score = f1_score(y_test, y_pred_test, average='macro') 
    recall = recall_score(y_test, y_pred_test, average='macro')  
    precision = precision_score(y_test, y_pred_test, average='macro')  
    kfold = cross_val_score(estimator = lg, X = X[train_indices], y = y[train_indices], cv = 5)

    print("Normalize Values")
    print('Confusion Matrix: \n',CM)
    print('Accuracy Score: ',acs)
    print('Recall:', recall)
    print('F1-Score:', f1score)
    print('Precision:', precision)
    print("5-Fold Cross Vaildation:", kfold.mean())
    print('\n')
    print(confusion_matrix(y_test,y_pred_test))
    print(classification_report(y_test,y_pred_test))

Normalize Values
Confusion Matrix: 
 [[5098  109]
 [2133  898]]
Accuracy Score:  0.72784656470017
Recall: 0.6376692492664464
F1-Score: 0.6322602903865282
Precision: 0.7983888743393123
5-Fold Cross Vaildation: 0.8126532421657373


[[5098  109]
 [2133  898]]
             precision    recall  f1-score   support

        0.0       0.71      0.98      0.82      5207
        1.0       0.89      0.30      0.44      3031

avg / total       0.77      0.73      0.68      8238

Normalize Values
Confusion Matrix: 
 [[4000 1207]
 [ 355 2676]]
Accuracy Score:  0.8103908715707696
Recall: 0.8255367983243631
F1-Score: 0.8053633134774334
Precision: 0.8038211841010877
5-Fold Cross Vaildation: 0.819723511454481


[[4000 1207]
 [ 355 2676]]
             precision    recall  f1-score   support

        0.0       0.92      0.77      0.84      5207
        1.0       0.69      0.88      0.77      3031

avg / total       0.83      0.81      0.81      8238

Normalize Values
Confusion Matrix: 
 [[3981 1226]
 [ 37

# K5 model

In [18]:
dataK5 = pickle.load(open("data/feature_selection/feature_k=5.pkl",'rb'))
Num5 = dataK5['numerical'][:,:27]
Cat5 = dataK5['categorical'][:,:5]

print(dataK5['categorical'].shape)
print(dataK5['numerical'].shape)


X = np.concatenate((Num5,Cat5),axis=1)

y = []
for i in range(41188):
    y.append(dataK5['categorical'][i][26])

y = np.asarray(y)
kf = KFold(n_splits = 5, random_state= 35)
for train_indices, test_indices in kf.split(X):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)
    lg = LogisticRegression()
    lg = lg.fit(X[train_indices], y[train_indices])
    y_pred_test = lg.predict(X_test)

    CM = confusion_matrix(y_pred=y_pred_test, y_true=y_test)
    acs = accuracy_score(y_true=y_test, y_pred=y_pred_test, normalize=True, sample_weight=None)
    f1score = f1_score(y_test, y_pred_test, average='macro') 
    recall = recall_score(y_test, y_pred_test, average='macro')  
    precision = precision_score(y_test, y_pred_test, average='macro')  
    kfold = cross_val_score(estimator = lg, X = X[train_indices], y = y[train_indices], cv = 5)

    print("Normalize Values")
    print('Confusion Matrix: \n',CM)
    print('Accuracy Score: ',acs)
    print('Recall:', recall)
    print('F1-Score:', f1score)
    print('Precision:', precision)
    print("5-Fold Cross Vaildation:", kfold.mean())
    print(confusion_matrix(y_test,y_pred_test))
    print(classification_report(y_test,y_pred_test))
    print('\n')



(41188, 28)
(41188, 5)
Normalize Values
Confusion Matrix: 
 [[ 180  976]
 [ 187 6895]]
Accuracy Score:  0.8588249575139597
Recall: 0.5646521861065971
F1-Score: 0.5792992699076058
Precision: 0.6832318617267471
5-Fold Cross Vaildation: 0.6254324734446131
[[ 180  976]
 [ 187 6895]]
             precision    recall  f1-score   support

        0.0       0.49      0.16      0.24      1156
        1.0       0.88      0.97      0.92      7082

avg / total       0.82      0.86      0.83      8238



Normalize Values
Confusion Matrix: 
 [[ 151 1005]
 [ 155 6927]]
Accuracy Score:  0.8591891235736829
Recall: 0.5543681823112154
F1-Score: 0.5646525623052775
Precision: 0.6833810427852431
5-Fold Cross Vaildation: 0.6139301972685888
[[ 151 1005]
 [ 155 6927]]
             precision    recall  f1-score   support

        0.0       0.49      0.13      0.21      1156
        1.0       0.87      0.98      0.92      7082

avg / total       0.82      0.86      0.82      8238



Normalize Values
Confusion Ma